-- =========================================================
-- FLAMINGO DJ - TEMP EDIT QUEUE
-- =========================================================
-- MASTER_CLEAN.db stays local.
-- Supabase stores ONLY small pending changes.
-- =========================================================

create table if not exists public.pending_track_edits (
  id bigint generated by default as identity primary key,

  user_id uuid not null
    default auth.uid()
    references auth.users(id)
    on delete cascade,

  song_id text not null,

  master_changes jsonb not null
    default '{}'::jsonb,

  dj_changes jsonb not null
    default '{}'::jsonb,

  status text not null
    default 'pending'
    check (
      status in (
        'pending',
        'applying',
        'applied',
        'error'
      )
    ),

  last_error text,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  applied_at timestamptz,

  unique (
    user_id,
    song_id
  )
);

create index if not exists
  idx_pending_track_edits_status
on public.pending_track_edits (
  status,
  updated_at
);

alter table
  public.pending_track_edits
enable row level security;

drop policy if exists
  "pending edits select own"
on public.pending_track_edits;

create policy
  "pending edits select own"
on public.pending_track_edits
for select
to authenticated
using (
  user_id = auth.uid()
);

drop policy if exists
  "pending edits insert own"
on public.pending_track_edits;

create policy
  "pending edits insert own"
on public.pending_track_edits
for insert
to authenticated
with check (
  user_id = auth.uid()
);

drop policy if exists
  "pending edits update own"
on public.pending_track_edits;

create policy
  "pending edits update own"
on public.pending_track_edits
for update
to authenticated
using (
  user_id = auth.uid()
)
with check (
  user_id = auth.uid()
);

-- ---------------------------------------------------------
-- Merge multiple edits of the SAME SongID into one row.
-- ---------------------------------------------------------

create or replace function
  public.queue_track_edit(
    p_song_id text,
    p_master_changes jsonb,
    p_dj_changes jsonb
  )
returns public.pending_track_edits
language plpgsql
security invoker
set search_path = public
as $$
declare
  result_row
    public.pending_track_edits;
begin
  if auth.uid() is null then
    raise exception
      'Authentication required';
  end if;

  insert into public.pending_track_edits (
    user_id,
    song_id,
    master_changes,
    dj_changes,
    status,
    last_error,
    updated_at,
    applied_at
  )
  values (
    auth.uid(),
    p_song_id,
    coalesce(
      p_master_changes,
      '{}'::jsonb
    ),
    coalesce(
      p_dj_changes,
      '{}'::jsonb
    ),
    'pending',
    null,
    now(),
    null
  )
  on conflict (
    user_id,
    song_id
  )
  do update set
    master_changes =
      public.pending_track_edits
        .master_changes
      ||
      excluded.master_changes,

    dj_changes =
      public.pending_track_edits
        .dj_changes
      ||
      excluded.dj_changes,

    status =
      'pending',

    last_error =
      null,

    updated_at =
      now(),

    applied_at =
      null
  returning *
  into result_row;

  return result_row;
end;
$$;

grant execute
on function
  public.queue_track_edit(
    text,
    jsonb,
    jsonb
  )
to authenticated;


-- =========================================================
-- AUTH SETUP NOTE
-- =========================================================
-- In Supabase Dashboard:
-- Authentication -> Providers -> Email -> Enable Email
--
-- Create your own user:
-- Authentication -> Users -> Add user
--
-- Do NOT add anonymous write policies.
-- The React app uses the normal anon key + authenticated user session.
