import type { QaCheckItem } from "../types/finalQa";

export const FINAL_QA_TEMPLATE: readonly QaCheckItem[] = [
  {
    id: "core-library",
    category: "core-flow",
    title: "Library loads correctly",
    description: "Open Tracks / Library and confirm tracks load, search works, filters work and the table remains usable.",
    status: "pending",
    notes: "",
  },
  {
    id: "core-playlists",
    category: "core-flow",
    title: "Playlist workflow",
    description: "Open playlists, open playlist detail, add/remove tracks and confirm state persists.",
    status: "pending",
    notes: "",
  },
  {
    id: "core-match",
    category: "core-flow",
    title: "Match Songs",
    description: "Verify Same Style / Cross Style results, BPM-first ranking and Key/Camelot information.",
    status: "pending",
    notes: "",
  },
  {
    id: "core-generate",
    category: "core-flow",
    title: "Generate Set",
    description: "Generate a set, apply Venue History and confirm BPM, phase blocks and Historical Track Priority are applied.",
    status: "pending",
    notes: "",
  },
  {
    id: "core-live",
    category: "core-flow",
    title: "Live session",
    description: "Start Live, move through tracks and confirm Current Set and active-track state update correctly.",
    status: "pending",
    notes: "",
  },
  {
    id: "core-audience",
    category: "core-flow",
    title: "Audience Response",
    description: "Record audience responses and confirm they are saved to the live session.",
    status: "pending",
    notes: "",
  },
  {
    id: "core-analysis",
    category: "core-flow",
    title: "End & Analyze",
    description: "End a session and verify Performance History, DJ Coach, Venue Coach and Time-of-Night Learning update.",
    status: "pending",
    notes: "",
  },

  {
    id: "persist-refresh",
    category: "persistence",
    title: "Browser refresh persistence",
    description: "Refresh the browser and confirm Current Set, Event Profile and relevant local state survive correctly.",
    status: "pending",
    notes: "",
  },
  {
    id: "persist-cloud-push",
    category: "persistence",
    title: "Cloud Push",
    description: "Push Local → Cloud and verify rows update in Supabase.",
    status: "pending",
    notes: "",
  },
  {
    id: "persist-cloud-pull",
    category: "persistence",
    title: "Cloud Pull",
    description: "Pull Cloud → Local and confirm the app reloads with cloud state.",
    status: "pending",
    notes: "",
  },
  {
    id: "persist-recovery",
    category: "persistence",
    title: "Recovery checkpoint",
    description: "Confirm Cloud Pull creates a recovery checkpoint and Restore Checkpoint works.",
    status: "pending",
    notes: "",
  },
  {
    id: "persist-backup",
    category: "persistence",
    title: "Backup / Restore",
    description: "Download, validate and restore a full backup successfully.",
    status: "pending",
    notes: "",
  },

  {
    id: "ui-empty",
    category: "ui",
    title: "Empty states",
    description: "Check pages and panels with no playlist, no history, no venue data or no current set.",
    status: "pending",
    notes: "",
  },
  {
    id: "ui-scroll",
    category: "ui",
    title: "Scroll / long panels",
    description: "Check Live, Analytics, Set Generator and long tables for clipped content or unusable scrolling.",
    status: "pending",
    notes: "",
  },
  {
    id: "ui-modals",
    category: "ui",
    title: "Modal behavior",
    description: "Open and close modals repeatedly and verify overlays and close controls work.",
    status: "pending",
    notes: "",
  },

  {
    id: "responsive-laptop",
    category: "responsive",
    title: "Laptop width",
    description: "Test around 1366×768 and confirm tables, Live panels and modals remain usable.",
    status: "pending",
    notes: "",
  },
  {
    id: "responsive-narrow",
    category: "responsive",
    title: "Narrow window",
    description: "Reduce browser width and confirm no major overlaps or navigation failures.",
    status: "pending",
    notes: "",
  },

  {
    id: "perf-large-library",
    category: "performance",
    title: "Large library interaction",
    description: "Search, filter and scroll the library and confirm the UI remains responsive.",
    status: "pending",
    notes: "",
  },
  {
    id: "perf-match",
    category: "performance",
    title: "Match calculation responsiveness",
    description: "Open Match Songs repeatedly on different tracks and watch for long stalls.",
    status: "pending",
    notes: "",
  },
  {
    id: "perf-generator",
    category: "performance",
    title: "Set generator responsiveness",
    description: "Generate multiple sets and confirm the modal remains responsive.",
    status: "pending",
    notes: "",
  },

  {
    id: "prod-build",
    category: "production",
    title: "Production build",
    description: "Run npm run build and confirm TypeScript + Vite finish without errors.",
    status: "pending",
    notes: "",
  },
  {
    id: "prod-diagnostics",
    category: "production",
    title: "System Diagnostics",
    description: "Confirm Storage Schema, Local Storage Integrity and Supabase Configuration report OK.",
    status: "pending",
    notes: "",
  },
  {
    id: "prod-env",
    category: "production",
    title: "Production environment variables",
    description: "Confirm VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are configured in the production host.",
    status: "pending",
    notes: "",
  },
  {
    id: "prod-auth",
    category: "production",
    title: "Supabase Auth redirects",
    description: "Confirm the deployed domain is allowed in Supabase Authentication URL / redirect settings.",
    status: "pending",
    notes: "",
  },

  {
    id: "real-set",
    category: "real-world",
    title: "Real DJ session",
    description: "Use Flamingo during a rehearsal or real set and identify controls that are too slow or distracting.",
    status: "pending",
    notes: "",
  },
  {
    id: "real-learning",
    category: "real-world",
    title: "Venue learning quality",
    description: "After multiple sessions at one venue, review whether Venue Coach and phase learning are useful.",
    status: "pending",
    notes: "",
  },
];
